import {test} from "@playwright/test"
test("insert",async({page})=>{
    await page.goto("https://demoapps.qspiders.com/ui?scenario=1")
    await page.getByPlaceholder("Enter your name").click()
    await page.keyboard.insertText("harshitha")
    await page.waitForTimeout(2000)
    await page.keyboard.down(".")
    await page.waitForTimeout(2000)
    await page.keyboard.up(".")
    await page.keyboard.down("A")
    await page.waitForTimeout(2000)
    await page.keyboard.up("A")
    await page.waitForTimeout(2000)
    await page.keyboard.press("Tab")
    await page.waitForTimeout(2000)
    await page.keyboard.insertText("hars@1gmail.com")
    await page.waitForTimeout(2000)
    await page.keyboard.press("Control+A")
    await page.waitForTimeout(2000)
    await page.keyboard.press("Control+C")
    await page.waitForTimeout(2000)
    await page.keyboard.press("Tab")
    await page.waitForTimeout(2000)
    await page.keyboard.press("Control+V")
    await page.waitForTimeout(2000)
    await page.keyboard.press("Tab")
    await page.keyboard.press("Tab")     
    
    await page.waitForTimeout(2000)

})